version: '3.6'

networks:
  default: { name: carta }

services:

  evestidor-ui:
    image: evestidor/ui:local
    build: ./core-ui
    restart: unless-stopped
    container_name: ui
    ports:
      - 8000:8000
    volumes:
      - ./core-ui:/app:rw,cached

  evestidor-api-gateway:
    image: evestidor/api-gateway:local
    build: ./core-api-gateway
    restart: unless-stopped
    container_name: api-gateway
    ports:
      - 8001:8000
    volumes:
      - ./core-api-gateway:/app:rw,cached

  evestidor-event-stream:
    image: evestidor/event-stream:local
    build: ./core-event-stream
    restart: unless-stopped
    container_name: event-stream
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
      - "5672:5672"
      - "15672:15672"

  evestidor-svc-stock-manager:
    image: evestidor/svc-stock-manager:local
    build: ./svc-stock-manager
    restart: unless-stopped
    container_name: svc-stock-manager
    volumes:
      - ./svc-stock-manager:/app:rw,cached

  evestidor-svc-stock-manager-consumer:
    image: evestidor/svc-stock-manager:local
    build: ./svc-stock-manager
    command: python manage.py consume_prices
    restart: unless-stopped
    container_name: svc-stock-manager-consumer
    volumes:
      - ./svc-stock-manager:/app:rw,cached

  evestidor-svc-stock-prices:
    image: evestidor/svc-stock-prices:local
    build: ./svc-stock-prices
    restart: unless-stopped
    container_name: svc-stock-prices
    ports:
      - "8003:8000"
    volumes:
      - ./svc-stock-prices:/app:rw,cached

  evestidor-svc-stock-prices-consumer:
    image: evestidor/svc-stock-prices:local
    build: ./svc-stock-prices
    command: python manage.py consume_prices
    restart: unless-stopped
    container_name: svc-stock-prices-consumer
    volumes:
      - ./svc-stock-prices:/app:rw,cached

  evestidor-svc-stock-prices-tracker:
    image: evestidor/svc-stock-prices-tracker:local
    build: ./svc-stock-prices-tracker
    restart: unless-stopped
    container_name: svc-stock-prices-tracker
    volumes:
      - ./svc-stock-prices-tracker:/app:rw,cached
