version: '3.6'

networks:
  default: { name: evestidor }

services:

  lighttpd:
    image: gists/lighttpd:1.4.52
    volumes:
      - .config/:/etc/lighttpd:ro
    ports:
      - 8000:8000

  evestidor-ui:
    image: evestidor/ui:local
    build: ./core-ui
    restart: unless-stopped
    container_name: ui
    volumes:
      - ./core-ui:/app:rw,cached
    environment:
      ALLOWED_HOSTS: '*'
      DATABASE_URL: sqlite:///local.db
      DEBUG: "true"
      ENVIRONMENT: sandbox
      SECRET_KEY: secret1
      USE_WHITENOISE: "true"
      API_GATEWAY_URL: http://0.0.0.0:8000/api

  evestidor-api-gateway:
    image: evestidor/api-gateway:local
    build: ./core-api-gateway
    restart: unless-stopped
    container_name: api-gateway
    volumes:
      - ./core-api-gateway:/app:rw,cached
    environment:
      STOCK_MANAGER_URL: http://evestidor-stock-manager:8000

  evestidor-event-stream:
    image: evestidor/event-stream:local
    build: ./core-event-stream
    restart: unless-stopped
    container_name: event-stream
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
      - "5672:5672"
      - "15672:15672"

  evestidor-stock-manager:
    image: evestidor/stock-manager:master
    build: ./svc-stock-manager
    restart: unless-stopped
    container_name: stock-manager
    volumes:
      - ./svc-stock-manager:/app:rw,cached
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: "true"
      ENVIRONMENT: sandbox
      SECRET_KEY: secret1

  evestidor-stock-manager-consumer:
    image: evestidor/stock-manager:local
    build: ./svc-stock-manager
    command: python manage.py consume_prices
    restart: unless-stopped
    container_name: stock-manager-consumer
    volumes:
      - ./svc-stock-manager:/app:rw,cached
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: "true"
      ENVIRONMENT: sandbox
      SECRET_KEY: secret1

  evestidor-svc-stock-price-simulator:
    image: evestidor/stock-price-simulator:local
    build: ./svc-stock-price-simulator
    restart: unless-stopped
    container_name: stock-price-simulator
    volumes:
      - ./svc-stock-price-simulator:/app:rw,cached
