#!/bin/bash
set -e

function getLatestCode() {
    git checkout master
    git pull origin master
}

function pushImage() {
    config/push-image
}

echo "Pushing UI image"
cd core-ui
getLatestCode
pushImage
cd ..

echo "Pushing API Gateway image"
cd core-api-gateway
getLatestCode
pushImage
cd ..

echo "Pushing Stock manager image"
cd svc-stock-manager
getLatestCode
pushImage
cd ..
